# 改行を含む文字列の場合は、[項目名: |]とする。
development:
  private: |
    openssl rsa -in private -pubout -out public

test:
  private: |
    openssl rsa -in private -pubout -out public

production:
  private: |
    openssl rsa -in private -pubout -out public
